projectcaluma/ember-alexandria

addon/components/document-grid.hbs, addon/components/document-grid.js, app/styles/components/_document-grid.scss, app/styles/ember-alexandria.scss, package.json, yarn.lock
=> Fix uikit grid

package.json
Don't know what went wrong in #18
=> fix: start-proxy command

addon/components/document-details.hbs, addon/components/document-details.js, addon/models/file.js, package.json, tests/acceptance/documents-test.js, tests/dummy/mirage/factories/file.js, translations/de.yaml, translations/en.yaml, yarn.lock
This adds a list of all past files for this document and a
replace button to upload new files to the document.
=> feat(history): add history of files to the side-panel

addon/models/category.js, addon/models/tag.js
To match what the backend delivers.
=> fix(models): change some attributes to localized

addon/components/document-grid.hbs, addon/components/document-grid.js
It is conflicting with the documents service.
=> fix(document-grid): rename lastSuccessful alias

package.json, yarn.lock
=> feat(deps): switch from Uglify to Terser for code mangling

addon/components/search.hbs, addon/components/search.js, addon/routes/application.js
Enter inside a text-input submits the form which is a problem.
=> fix(search): add preventDefault to submit

addon/components/search.hbs
Having it on the DIV worked somehow. But it's still wrong.
=> fix(search): move onSubmit handler to correct element

addon/routes/application.js
because I didn't read the `isEmpty` documentation properly.
=> fix: reset document selection

.github/dependabot.yml, package.json, yarn.lock
Our apps are not yet ready for ember-data v4.
=> chore(deps): downgrade ember-data to v3.28.13

addon/components/single-document-details.hbs
button with href does not work
=> fix: fix history download

package.json, yarn.lock
See https://github.com/projectcaluma/ember-localized-model/pull/163
=> fix(deps): bump ember-localized-model to fix file rename bug

addon/components/document-card.js, tests/integration/components/document-card-test.js
and make comment on filename attribute more precise
=> fix(download): don't add extension if already present

addon/components/documents-side-panel.hbs, addon/components/mark-manager.hbs, addon/components/multi-document-details.hbs, addon/components/single-document-details.hbs, app/styles/components/_document-details.scss, app/styles/components/category-nav/_category.scss, config/icons.js, tests/integration/components/single-document-details-test.js, translations/de.yaml, translations/en.yaml
=> refactor(document-details): refactor styling and toggling of document detail view

addon/components/document-list-item.hbs, addon/components/document-list.hbs, addon/components/single-document-details.hbs, addon/components/single-document-details.js, addon/models/document.js, package.json, tests/dummy/mirage/factories/document.js, tests/integration/components/single-document-details-test.js, translations/de.yaml, translations/en.yaml, yarn.lock
Needs https://github.com/projectcaluma/alexandria/pull/372
=> feat(document): add manual document date

addon/services/documents.js
Reverts projectcaluma/ember-alexandria#596
=> Revert "fix(upload): upload files with the proper content type header"

addon/services/documents.js
Reverts projectcaluma/ember-alexandria#600
=> Revert "Revert "fix(upload): upload files with the proper content type header""

addon/components/category-nav/category.js, addon/components/document-card.hbs, addon/components/document-list-item.hbs, addon/components/document-view.hbs, addon/components/mark-manager.hbs, addon/components/mark-manager.js, addon/components/mark-manager/mark.hbs, addon/components/mark-manager/mark.js, addon/components/tag-filter.hbs, addon/components/tag-filter.js, addon/components/tag-manager.js, addon/controllers/application.js, addon/models/document.js, addon/models/mark.js, addon/routes/application.js, addon/services/config.js, addon/services/marks.js, addon/services/tags.js, tests/acceptance/documents-test.js, tests/acceptance/nav-test.js, tests/dummy/app/services/alexandria-config.js, tests/dummy/mirage/config.js, tests/dummy/mirage/factories/document.js, tests/dummy/mirage/factories/mark.js, tests/dummy/mirage/models/document.js, tests/dummy/mirage/models/mark.js, tests/integration/components/document-view-test.js, tests/integration/components/mark-manager-test.js, tests/integration/components/tag-filter-test.js, tests/unit/controllers/application-test.js
frontend part of https://github.com/projectcaluma/alexandria/pull/382
closes https://github.com/projectcaluma/ember-alexandria/issues/159
=> feat: integrate marks model

addon/components/document-grid.hbs, addon/components/document-view.hbs, addon/components/document-view.js, addon/components/tag-filter.hbs, addon/components/tag-filter.js, addon/routes/application.js, addon/services/tags.js, tests/acceptance/documents-test.js, tests/integration/components/document-card-test.js, tests/integration/components/document-view-test.js, tests/integration/components/tag-filter-test.js, tests/unit/services/tags-test.js
- Reset query parameters when reentering route
- Change tag suggestion filter to `istartswith`
- only show mark filters when they are set
=> Fix various bugs

package.json
=> chore(npm): fix repository definition in package.json

addon/components/document-view.js, addon/components/download-button.js, tests/acceptance/documents-test.js, tests/dummy/mirage/config.js, tests/helpers/assert-request.js, translations/en.yaml
Fixes regression introduced in 8261bbb3e283c9b8001e45dd200bc2cec0a67b65
=> fix(selection): fix regression in shift selection

addon/components/single-document-details.hbs, addon/components/single-document-details.js, app/styles/ember-alexandria.scss, package.json, pnpm-lock.yaml
updates from 4 to 7
fixes missing localization
closes https://github.com/projectcaluma/ember-alexandria/pull/701
=> fix: update and fix flatpickr integration

addon/components/single-document-details.hbs, addon/components/single-document-details.js, addon/models/file.js, addon/services/alexandria-config.js, tests/dummy/app/services/alexandria-config.js, translations/de.yaml, translations/en.yaml
=> feat: add web dav edit integration

addon/components/category-nav/category.hbs, app/styles/components/category-nav/_category.scss, package.json, pnpm-lock.yaml
* Enable rendering of markdown
* Change tooltip to uk-dropdown
* Set min-width to icon
=> fix(categories): format alexandria category descriptions

.gitignore, addon/adapters/application.js, addon/adapters/document.js, addon/models/document.js, addon/serializers/document.js, addon/services/alexandria-documents.js, ember-cli-build.js, tests/acceptance/documents-test.js, tests/dummy/app/adapters/document.js, tests/dummy/mirage/config.js, tests/dummy/mirage/factories/file.js, tests/unit/services/alexandria-documents-test.js, tests/unit/services/alexandria-tags-test.js
fixes  problem when uploading a file and the file gets rejected, leaving an empty document
=> feat: upload document and file in one request

addon/components/document-view.hbs, addon/components/file-search.hbs, translations/de.yaml
using position relative and absolute broke the UI (no document list visible, set height to 1000px and it appeared) in some cases.
Removing them did not change the look and feel of the UI therefore I feel that they are unnecessary and can be removed.
=> Fix layout

addon/components/document-delete-button.js, addon/components/document-list-item.hbs, addon/components/document-list.hbs, addon/components/file-search.hbs, tests/dummy/app/services/alexandria-config.js
fix link not having a model or being able to use an async function
add loading state
=> Document List Improvements

addon/components/category-nav/category.js, addon/components/document-list-item.hbs, tests/integration/components/category-nav/category-test.js
Dragging the preview image will move the document now.
Wasnt able to reproduce a wrong behavior on the card screen
=> fix(nav): upload of preview images

addon/components/document-list-item.hbs, addon/components/document-list.hbs, app/styles/_responsive.scss
=> fix: optimize responsive behavior of document list

addon/controllers/index.js, tests/unit/controllers/index-test.js
metainfo filters to file metainfo, expected would be document metainfo
=> fix(search): use correct filter on document list

addon/components/document-view.js, addon/controllers/index.js, tests/unit/controllers/index-test.js
forgot to test with instance view for #1068
=> fix(search): fix metainfo filter to differentiate search

addon/components/document-view.hbs, addon/components/document-view.js
fix forgotten replacement from https://github.com/projectcaluma/ember-alexandria/commit/1d407fe1f2adc94d4fa557799d0894f33cfbdf79
=> fix(upload): user correct category filter key

addon/services/alexandria-documents.js, tests/unit/services/alexandria-documents-test.js
Adds options to the ember documents service to:
- Mute the upload notification in some cases when it's used in the background
- Pass extra metainfo for the document upload
=> feat(upload): add optional parameters to the upload function

addon/components/category-nav/category.js, tests/integration/components/category-nav/category-test.js
Fixes https://github.com/projectcaluma/ember-alexandria/issues/1007
=> fix(upload): add router transition on drop upload on category

addon/services/alexandria-documents.js, tests/dummy/app/session-stores/application.js
fixes regression from https://github.com/projectcaluma/ember-alexandria/commit/4e6d533175e1501d7a0e89f5efe62d5fa0d03db6
=> Fix mime type checking for .msg files
