addon/serializers/file.js, app/serializers/file.js, tests/unit/serializers/category-test.js, tests/unit/serializers/document-test.js, tests/unit/serializers/file-test.js
Otherwise, the serializer of the consuming application will be
used.
=> fix(serializers): add file serializer for more control

tests/dummy/app/routes/application.js
The backend's fixtures are en English which leaves the user with
empty-string category names.
=> fix(dummy): update language to English to conform to backend

addon/components/document-details.hbs, addon/components/document-grid.js, tests/integration/components/document-details-test.js, translations/de.yaml, translations/en.yaml
This adds a small label and fixes some issues concerning the widths
of the save and close buttons.
=> feat(document-details): add label to document title and fix design

addon/components/document-card.hbs, addon/components/document-card.js, addon/components/document-delete-button.hbs, addon/components/document-delete-button.js, addon/components/document-details.hbs, addon/components/document-details.js, config/environment.js, tests/acceptance/documents-test.js, tests/integration/components/document-card-test.js, tests/integration/components/document-delete-button-test.js, tests/integration/components/document-details-test.js, translations/de.yaml, translations/en.yaml
This adds a component that provides a prompt and handles deletion.
I had to disable quite a few tests. I updated the tests but there is a problem with where ember-uikit places its modal dialogues. I tried using the master branch as there is a relevant update that hasn't been released but that didn't seem to make a difference.
=> feat(document-delete-buttom): add a prompt to the delete buttons

addon/components/document-details.hbs, addon/components/document-details.js
This change resets the matching tags when the search box is empty
and after adding a tag to the document. This also removes unneeded
queries when a tag already exists on the document and updates the
styling of the selected tags.
=> fix(document-details): reset matching tags and minor fixes

package.json, yarn.lock
The modal is not rendered in the rootElement specified in the config anymore. This causes css selectors to fail.
=> fix(deps): pin ember-uikit to 2.2.0 to fix floating test issue with modal and rootElement

addon/components/document-details.js, app/serializers/tag.js
Without the export the projects would have to provide their own
serializers for the tags. Plus, the language was hard-coded.
=> fix(app): export tag serializer to and remove hard-coded value

addon/components/document-details.js
Otherwise, we transform it to lower case for every tag we test against.
=> refactor(document-details): save lower cased search value in variable

addon/components/document-details.hbs
Using a link for close buttons is wrong anyway and I'd already created
the closePanel action to pass to the DeleteButton component.
=> refactor(document-details): reuse new close action with button

addon/components/tag-filter.hbs
Firefox doesn't like `javascript:void(0)`.
=> fix(tag-filter): change javascript: link to button

addon/models/tag.js
Localization doesn't really work in practice as there is no central tag administration that could deal with missing translations.
See https://github.com/projectcaluma/alexandria/pull/117
=> feat(models): change tag name to non-localized

.ember-cli, addon/components/document-upload-button.hbs
This changes the boolean attribute to the old-school/legacy notation
as the normal style doesn't seem to hold when importing the engine
in an Ember application.
=> fix(document-upload-button): update multiple attribute

addon/components/document-details.hbs, addon/components/document-details.js, addon/components/document-grid.hbs, addon/components/tag-filter.hbs, addon/components/tag-filter.js, addon/services/tags.js, app/services/tags.js, tests/dummy/mirage/factories/tag.js, tests/unit/services/tags-test.js
This allows for all the components to work on a shared instance.
Currently, we cannot update the tags in the TagFilter when adding
a new tag in the DocumentDetail.
=> refactor(tags): move tag handling to service

addon/components/document-grid.hbs, addon/components/document-grid.js, app/styles/components/_document-grid.scss, translations/de.yaml, translations/en.yaml
Documents can only be uploaded if a category is selected. This colors
the UI feedback in red and changes the text if no category is selected.
=> feat(document-grid): show a warning when files cannot be dropped

.github/workflows/test.yml
There is a bug upstream that breaks Ember Engine. As I didn't
find a way to work around this bug we decided to disable the
test for now.
=> fix: temporarily disable the ember-release test

addon/services/tags.js
Just as with the documents we only show the tags from the currently
selected dossier.
=> feat(tags): filter tags by meta value

addon/controllers/application.js, addon/models/document.js, addon/models/file.js, addon/models/tag.js, addon/routes/application.js, addon/services/config.js, addon/services/documents.js, addon/services/tags.js, tests/dummy/app/adapters/application.js, tests/dummy/app/templates/application.hbs, tests/dummy/mirage/factories/document.js, tests/dummy/mirage/factories/file.js, tests/dummy/mirage/factories/tag.js, tests/unit/controllers/application-test.js
As a user can be in multiple groups we need a way to choose which
group will be used for created-by (and modified-by). Plus, we only
fetch the documents with a matching created-by value.
=> feat: introduce created-by to documents, files, and tags

addon/components/document-details.hbs, addon/components/document-details.js, translations/de.yaml, translations/en.yaml
This uses the same idea/logic as the title edit form.
=> feat(document-details): add form to edit the document's description

.github/workflows/test.yml
This reverts PR #187 as they have fixed the problem upstream.
https://github.com/ember-engines/ember-engines/releases/tag/v0.8.9
=> fix: reenable the ember-release test

addon/components/document-details.hbs, translations/de.yaml, translations/en.yaml
This removes the link-reset from the "add" link, adds a title to the description (as per customer request), enlarges the
textarea, and updates the markup to fit.
=> feat(document-details): update UI for description and its form

addon/routes/application.js
Otherwise, Ember will not detect outside changes to the query params.
=> fix(route): add queryParams config to route

package.json, yarn.lock
Building with 3.6.15 doesn't work and 3.6.12 to 3.6.14 build
but don't finish as the tests freeze the browser. And Babel
has a problem transpiling TypeScript at 7.12.13.
=> fix(deps): add resolution for UIkit and @babel/parser

addon/routes/application.js, package.json
Without the empty model hook the route throws if activeRoute is set.
And without the additional param configuration those won't work.
No idea why I didn't catch this last time. Maybe the CLI didn't rebuild properly or something :shrug: 
https://github.com/projectcaluma/ember-alexandria/pull/200
=> fix(routes): add empty model hook and param options to route

README.md, addon/components/document-details.hbs, addon/helpers/resolve-group.js, addon/helpers/resolve-user.js, addon/routes/application.js, addon/services/config.js, app/helpers/resolve-group.js, app/helpers/resolve-user.js, tests/integration/helpers/resolve-group-test.js, tests/integration/helpers/resolve-user-test.js
The config service has an identity function as default resolvers.
Depends on #207
=> feat(config): add resolver for user and group IDs 

addon/components/document-details.hbs
As a title as there is not enough space.
=> feat(document-details): add filename to file history

addon/components/document-card.js, tests/integration/components/document-card-test.js, tests/integration/components/document-details-test.js
The document title has no extension but the user's OS wants one.
=> fix(document-card): add file extension from last upload to filename

.github/workflows/test.yml
This is only meant for temporarly purpose until we find a solution
for this scenario to work
=> chore: disable ember-release scenario for tests and use node v12

addon/components/document-view.js, addon/components/single-document-details.hbs, addon/components/single-document-details.js, addon/services/documents.js, tests/integration/components/single-document-details-test.js
The multi-document selection, with CTRL+A disabled the usage of CTRL+A in side panel form fields. This fix addresses this.
=> fix: enable ctrl-a in side panel

addon/components/document-card.js, addon/components/document-view.js
The zip-download as it currently is in main does not work with all alexandria backend implementations.
As an example, the SoBau alexandria backend requires the `document-meta` to be set which this PR does.
=> fix: zip download

addon/components/category-nav/category.hbs, addon/components/category-nav/category.js, addon/components/document-list-item.hbs, addon/components/tag-filter.hbs, addon/routes/application.js, tests/acceptance/documents-test.js
This stops the tag filter from clearing when selecting a document.
On category change the tags still get reset. Otherwise, depending on the setup of categories and tags, a user might end up with having a tag selected that they can't deselect after changing the category.
=> fix: don't clear tag selection when selecting a document

addon/routes/application.js
fix: reset document selection on navigating away
Depending on how ember alexandria is used we might have to reset the document selection on navigation.
=> fix: reset document selection on navigating away

addon/components/document-card.js, addon/components/single-document-details.hbs, addon/controllers/application.js, addon/models/category.js, addon/models/document.js, addon/models/file.js, addon/models/tag.js, addon/services/documents.js, tests/acceptance/documents-test.js, tests/dummy/mirage/factories/file.js, tests/integration/components/document-card-test.js, tests/integration/components/single-document-details-test.js, tests/unit/controllers/application-test.js
alexandria renamed meta to metadata and type to variant
relies on https://github.com/projectcaluma/alexandria/pull/285, #414
=> fix: use renamed fields from the backend

addon/services/tags.js, tests/dummy/mirage/config.js
Previous implementation has a prod only bug where the line `(await document.tags).push(tag)` produced the error `(intermediate value).push is not a function`
=> fix(tags): improve adding a new tag

README.md, addon/components/single-document-details.js, addon/components/tag-manager.hbs, addon/components/tag-manager.js, addon/services/config.js, addon/services/tags.js, tests/integration/components/documents-side-panel-test.js, tests/integration/components/mark-manager-test.js, tests/unit/services/tags-test.js
improve tag service by moving tag manager parts out
improved error handling in tag service
requires backend change  https://github.com/projectcaluma/alexandria/pull/387
=> fix(tags): improve tag manager

.github/workflows/ci.yml, tests/dummy/config/ember-try.js
BREAKING CHANGE: Remove support for deprecated ember LTS versions 4.4 and 4.8.
=> chore(compatibility): add compatibility tests for ember LTS 5.4

addon/adapters/file.js, addon/models/file.js, addon/serializers/file.js, addon/services/alexandria-documents.js, tests/acceptance/documents-test.js, tests/dummy/app/adapters/file.js, tests/dummy/mirage/config.js, tests/unit/adapters/file-test.js, tests/unit/serializers/file-test.js, tests/unit/services/alexandria-documents-test.js
BREAKING CHANGE: Requires alexandria backend v3.0.0-beta.3
=> feat(api): upload files directly via alexandria API

README.md, addon/components/document-view.hbs, addon/components/document-view.js, addon/components/documents-side-panel.hbs, addon/components/single-document-details.hbs, addon/components/single-document-details.js, addon/models/file.js, addon/services/alexandria-config.js, tests/dummy/app/services/alexandria-config.js, tests/integration/components/single-document-details-test.js, translations/de.yaml, translations/en.yaml
Integrates backend endpoint to convert docx, odt to pdf
requires https://github.com/projectcaluma/alexandria/pull/463
=> feat: add button to convert to pdf

addon/components/document-view.js
part of #723
behavior is still the same, only change is the fix for the initial selection
=> fix(documents): fix inital selection with ctrl

addon/components/document-view.js
This fixes an issue when uploading a file via drag & drop:
This might have been a regression from moving `afterUpload` to the `document-upload-button` component? I couldn't find any references to the method anywhere else ...
=> fix: remove call of inexistent function afterUpload

addon/services/alexandria-documents.js
This is an ugly workaround for the lacking support of `file.type` for msg files.
=> fix(mime): allow upload of msg files

addon/services/alexandria-documents.js
`file.type` is an empty string not null, therefore not triggering the alternative logic
=> fix(mime): softer mime type checking

addon/serializers/document.js, tests/unit/serializers/document-test.js, translations/en.yaml
prevents error from backend for trying to serialize the content attr when patching after an upload.
drive by translation fix
=> fix: remove content attr in serialization for patch

addon/components/document-delete-button.js, addon/services/alexandria-documents.js, tests/integration/components/document-card-test.js, tests/integration/components/document-delete-button-test.js, tests/integration/components/single-document-details-test.js
fixes bug when deleting multiple the last one keeps the side panel open, eventhough it does not exist anymore
and its **10x** or so faster (promise.all ftw)
=> fix(delete): delete concurrently and clean up correctly

README.md, addon/components/single-document-details.js, addon/services/alexandria-config.js, tests/integration/components/single-document-details-test.js, translations/de.yaml, translations/en.yaml
uses https://github.com/projectcaluma/alexandria/pull/549
=> refactor: use webdav endpoint

app/styles/components/_document-list.scss
How it is:
What the fix does (restores previous look):
Same 3 selected in both images
not quite sure why changing the css class path does this, probably something with precedence/ specificity winning when using the new path
=> fix(css): selected color should win over striped table

addon/components/mark-manager/mark.hbs, app/styles/components/_document-details.scss
A description for some marks might be helpful. Currently they are not visible anywhere.
Display them like the description of the categories.
Screenshot is weird, the tooltip should be visible above, but creating a screenshot hides it. Cursor is on middle mark.
=> feat(mark): display description

addon/services/alexandria-documents.js
It seems that not all mime types can be mapped to file extensions. The concrete case that triggered this fix was "image/vnd.dwg".
=> fix: filter empty extensions in error message

addon/components/document-view.js, addon/components/search.hbs, addon/components/search.js
=> fix(search-input): make sure text selection works in search bar

addon/components/single-document-details.hbs
- Smaller font size for the document title in the side panel (to accomodate for long file names)
- Fix responsive behavior of input field for edit title form
=> refactor(single-document-details): document title and edit title form

addon/services/alexandria-documents.js, tests/acceptance/documents-test.js, tests/integration/components/category-nav/category-test.js, tests/unit/services/alexandria-documents-test.js
The current lookup for the mimeType was just done by checking the name / file-extension in the name, which lead to errors when moving documents to other categories when someone changed the name of the document to something without an valid extension
e.g.
1. File "ABC.pdf" was uploaded
2. ABC renamed to "ABC"
3. User wants to move it to other category => failed
This PR fixes this, so that the File could be moved even when it's named "ABC", because it is checking the explicit mimeType (which was determined by the libmagic python lib in the backend)
=> fix(documents): add mimeType lookup for mimeType/file-extension check

addon/components/documents-side-panel.hbs, addon/components/multi-document-details.hbs, addon/components/multi-document-details.js, addon/components/single-document-details.hbs, addon/components/single-document-details.js, addon/services/alexandria-documents.js, tests/acceptance/documents-test.js, tests/dummy/mirage/config.js, translations/de.yaml, translations/en.yaml, translations/it.yaml
95% of this is @nlzet's work, I just added buttons instead of drag & drop :grin:
=> feat(document): add copy button

addon/components/single-document-details.hbs, addon/components/single-document-details.js, addon/services/alexandria-config.js, tests/acceptance/documents-test.js, tests/dummy/app/services/alexandria-config.js, translations/de.yaml, translations/en.yaml, translations/it.yaml
When the document title does not match the original filename, show the original filename in the single document details.
=> feat(document-details): show original filename

addon/services/alexandria-documents.js
When an error occurs during the upload of a file, the success notification should not be shown.
**Example:**
However, on multi-upload the the notification may be shown if at least one upload was succesful, e.g.:
=> fix(upload): only show success notification on successful upload

addon/components/category-nav/category.js, addon/services/alexandria-documents.js, translations/de.yaml, translations/en.yaml, translations/it.yaml
Currently we have the problem, that when you move a document to a category, where you don't have permission to see it, it won't show in the target category. Therefore we denied it in the permission layer, but to give the user a chance to move / copy it anyways we want to provide him a new confirm-dialog, in which the user can decide to create a copy of the chosen document in that target category - but only if the user has no permission to move the document.
=> feat: ask to create copy in target category when moving a document
